// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID   int64
	Name string
}

type GroupTag struct {
	GroupID int64
	TagID   int64
}

type Tag struct {
	ID  int64
	Tag string
}

type Task struct {
	ID    int64
	Title string
	// Content of the post
	Body      string
	UserID    int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

type TaskTag struct {
	TasksID int64
	TagID   int64
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type UserGroup struct {
	GroupID int64
	UserID  int64
}

type UserTag struct {
	UserID int64
	TagID  int64
}
